version: '3.8'

services:
  wa-logger:
    build: .
    container_name: wa-logger
    restart: unless-stopped
    volumes:
      - ./auth_data:/usr/src/app/.wwebjs_auth
      - ./logs:/usr/src/app/logs
      - ./index.js:/usr/src/app/index.js