version: '3.8'

services:
  wa-logger:
    build: .
    container_name: wa-logger
    restart: unless-stopped
    init: true
    stop_grace_period: 2m
    
    deploy:
      resources:
        limits:
          cpus: '0.75'        
          memory: 800M        
        reservations:
          memory: 256M        

    volumes:
      - ./auth_data:/usr/src/app/.wwebjs_auth
      - ./logs:/usr/src/app/logs
      - ./index.js:/usr/src/app/index.js